### PR TITLE
Menu branch

### PR DESCRIPTION
**Pull request by spencovault**
Built button struct and setters for all of the fields in the button struct.

### CODE REVIEW

**Review by brettsalyer — APPROVED** [review]
Since I helped develop this I know it's OK. Approved

**Review by ikbenhomer — APPROVED** [review]
Code seems to logically make sense and should work correctly. Approved

**Comment by caleb-austin** [comment]
Code seems to make sense to me!

**Review by caleb-austin — APPROVED** [review]

**Comment by Kwask** [comment]
Looks good to me as well!

**Review by Kwask — APPROVED** [review]

**Pull request merged**
